package com.accessmanagement.model;

public class Software {
    private Long id;
    private String name;
    private String description;
    private String accessLevels;

    public Software(Long id, String name, String description, String accessLevels) {
        this.id = id;
        this.name = name;
        this.description = description;
        this.accessLevels = accessLevels;
    }

    public Software(String name, String description, String accessLevels) {
        this.id = null; // ID will be generated by database
        this.name = name;
        this.description = description;
        this.accessLevels = accessLevels;
    }

    // Getters and setters

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public String getAccessLevels() {
        return accessLevels;
    }

    public void setAccessLevels(String accessLevels) {
        this.accessLevels = accessLevels;
    }
}
